spring:
  application:
    name: distributed-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/distributed-demo
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
app:
  cors:
    allowed-origin: http://localhost:4200